//! Golden scripted session for the reward-modulated learning lab
//! (`/labs/plasticity/`, GitHub #17 / RM-1654).
//!
//! `src/data/plasticity/scripted-session.v1.json` is generated by this file
//! from [`SCRIPTED_SESSION`] and [`SCRIPTED_SESSION_SEED`]. It pins, per step,
//! the reward input, the `limbic-critic` modulators, the input and output
//! spikes, the membrane and threshold bits, and every weight whose bits
//! changed, plus the final weights, thresholds, eligibility traces, and the
//! frozen probe before and after. The same file is replayed through the
//! committed labs WASM package by `test/plasticity-lab.test.mjs` and, on
//! demand, in the browser. Never hand-edit it; regenerate with:
//!
//! ```text
//! cargo +1.98.1 test --manifest-path crates/neuromorphic-adapter/Cargo.toml --locked --features plasticity --test plasticity_session regenerate_plasticity_golden -- --ignored --exact
//! ```

use limbic_critic::SimpleCritic;
use neuromorphic_adapter::plasticity::{
    INITIAL_THRESHOLD, INITIAL_WEIGHT, LAB_CHANNELS, LAB_NEURONS, LabProbe, LabStep,
    PLASTICITY_LAB_VERSION, PROBE_AMPLITUDE, PROBE_STEPS, PROBE_STREAM, PlasticityLab, REWARD_LR,
    RewardEvent, SCRIPTED_SESSION, SCRIPTED_SESSION_SEED, ScriptedSessionTrace, Stimulus,
    TAU_ELIGIBILITY, TRAINING_AMPLITUDE, run_scripted_session,
};
use serde_json::{Value, json};
use std::path::PathBuf;

const GOLDEN_PATH: &str = "src/data/plasticity/scripted-session.v1.json";
const GOLDEN: &str = include_str!("../../../src/data/plasticity/scripted-session.v1.json");
const GOLDEN_FORMAT: &str = "shipoftheseus.plasticity-session";
const GENERATOR: &str = "crates/neuromorphic-adapter/tests/plasticity_session.rs";
const REGENERATE: &str = "cargo +1.98.1 test --manifest-path crates/neuromorphic-adapter/Cargo.toml --locked --features plasticity --test plasticity_session regenerate_plasticity_golden -- --ignored --exact";
const LOCKFILE: &str = include_str!("../Cargo.lock");

fn bits(values: &[f32]) -> Vec<u32> {
    values.iter().map(|value| value.to_bits()).collect()
}

fn probe_json(probe: &LabProbe) -> Value {
    json!({
        "pattern_a_spikes": probe.pattern_a_spikes,
        "pattern_b_spikes": probe.pattern_b_spikes,
    })
}

fn step_json(step: &LabStep, new_episode: bool) -> Value {
    json!({
        "step": step.step,
        "episode": step.episode,
        "new_episode": new_episode,
        "stimulus": step.stimulus.name(),
        "event": step.event.name(),
        "objective_bits": step.observation.objective.to_bits(),
        "stress_bits": step.observation.stress.to_bits(),
        "modulator_bits": bits(&step.modulators),
        "input_spikes": step.input_spikes,
        "output_spikes": step.output_spikes,
        "membrane_bits": bits(&step.membrane_potentials),
        "threshold_bits": bits(&step.thresholds),
        "weight_changes": step
            .weight_changes
            .iter()
            .map(|change| [change.neuron, change.channel, change.before_bits, change.after_bits])
            .collect::<Vec<_>>(),
    })
}

/// The committed golden: top-level keys in a fixed order, one compact JSON
/// object per step so the file stays reviewable.
fn render_golden(trace: &ScriptedSessionTrace, final_eligibility: &[f32]) -> String {
    let fields: Vec<(&str, Value)> = vec![
        ("format", json!(GOLDEN_FORMAT)),
        ("format_version", json!(1)),
        ("lab_version", json!(PLASTICITY_LAB_VERSION)),
        ("generator", json!(GENERATOR)),
        ("regenerate", json!(REGENERATE)),
        ("seed", json!(trace.seed.to_string())),
        (
            "network",
            json!({
                "lif_neurons": LAB_NEURONS,
                "channels": LAB_CHANNELS,
                "initial_weight_bits": INITIAL_WEIGHT.to_bits(),
                "initial_threshold_bits": INITIAL_THRESHOLD.to_bits(),
                "tau_eligibility_bits": TAU_ELIGIBILITY.to_bits(),
                "reward_lr_bits": REWARD_LR.to_bits(),
                "training_amplitude_bits": TRAINING_AMPLITUDE.to_bits(),
                "probe_amplitude_bits": PROBE_AMPLITUDE.to_bits(),
                "probe_steps": PROBE_STEPS,
                "probe_stream": PROBE_STREAM.to_string(),
            }),
        ),
        ("probe_before", probe_json(&trace.probe_before)),
        ("steps", Value::Null),
        ("final_weight_bits", json!(bits(&trace.final_weights))),
        ("final_threshold_bits", json!(bits(&trace.final_thresholds))),
        ("final_eligibility_bits", json!(bits(final_eligibility))),
        ("probe_after", probe_json(&trace.probe_after)),
    ];
    let mut out = String::from("{\n");
    for (index, (key, value)) in fields.iter().enumerate() {
        let rendered = if *key == "steps" {
            let lines = trace
                .steps
                .iter()
                .zip(SCRIPTED_SESSION)
                .map(|(step, entry)| {
                    format!(
                        "    {}",
                        serde_json::to_string(&step_json(step, entry.new_episode)).unwrap()
                    )
                })
                .collect::<Vec<_>>();
            format!("[\n{}\n  ]", lines.join(",\n"))
        } else {
            serde_json::to_string(value).unwrap()
        };
        out.push_str(&format!(
            "  {}: {rendered}",
            serde_json::to_string(key).unwrap()
        ));
        out.push_str(if index + 1 < fields.len() {
            ",\n"
        } else {
            "\n"
        });
    }
    out.push_str("}\n");
    out
}

/// Replays the script and returns the trace plus the final eligibility traces.
fn replay(seed: u64) -> (ScriptedSessionTrace, Vec<f32>) {
    let trace = run_scripted_session(seed, &SCRIPTED_SESSION).expect("scripted session runs");
    let mut lab = PlasticityLab::new(seed);
    for entry in SCRIPTED_SESSION {
        if entry.new_episode {
            lab.new_episode();
        }
        lab.step(entry.stimulus, entry.event).expect("step");
    }
    assert_eq!(lab.weights(), trace.final_weights);
    (trace, lab.eligibility())
}

fn generated_golden() -> String {
    let (trace, eligibility) = replay(SCRIPTED_SESSION_SEED);
    render_golden(&trace, &eligibility)
}

#[test]
fn the_committed_golden_matches_a_fresh_native_replay() {
    assert_eq!(
        GOLDEN.replace("\r\n", "\n"),
        generated_golden(),
        "{GOLDEN_PATH} is stale; regenerate it with:\n{REGENERATE}"
    );
}

#[test]
fn the_golden_is_versioned_and_names_its_generator() {
    let golden: Value = serde_json::from_str(GOLDEN).expect("golden is JSON");
    assert_eq!(golden["format"], GOLDEN_FORMAT);
    assert_eq!(golden["format_version"], 1);
    assert_eq!(golden["lab_version"], PLASTICITY_LAB_VERSION);
    assert_eq!(golden["generator"], GENERATOR);
    assert_eq!(golden["seed"], SCRIPTED_SESSION_SEED.to_string());
    assert_eq!(
        golden["steps"].as_array().map(Vec::len),
        Some(SCRIPTED_SESSION.len())
    );
}

#[test]
fn replay_is_deterministic_for_a_seed_and_differs_across_seeds() {
    assert_eq!(replay(SCRIPTED_SESSION_SEED), replay(SCRIPTED_SESSION_SEED));
    // The seed drives neuromod's Bernoulli input spike times, which decide
    // the eligibility traces and therefore the learned weights.
    assert_ne!(
        replay(SCRIPTED_SESSION_SEED).0.final_weights,
        replay(SCRIPTED_SESSION_SEED + 1).0.final_weights
    );
}

#[test]
fn reward_input_passes_through_limbic_critic_unchanged_into_neuromod() {
    let (trace, _) = replay(SCRIPTED_SESSION_SEED);
    for step in &trace.steps {
        let expected = SimpleCritic::try_assess(&step.event.observation()).expect("finite");
        assert_eq!(
            step.modulators,
            [
                expected.dopamine,
                expected.serotonin,
                expected.acetylcholine,
                expected.norepinephrine
            ],
            "step {}",
            step.step
        );
        match step.event {
            RewardEvent::Reward => assert_eq!(step.modulators, [1.0, 0.0, 0.0, 0.0]),
            RewardEvent::Penalty => assert_eq!(step.modulators, [0.0, 0.0, 0.0, 1.0]),
            RewardEvent::None => assert_eq!(step.modulators, [0.0; 4]),
        }
    }
}

/// Largest `|after - before|` among a step's changed weights.
fn largest_weight_change(step: &LabStep) -> f32 {
    step.weight_changes
        .iter()
        .map(|change| {
            (f32::from_bits(change.after_bits) - f32::from_bits(change.before_bits)).abs()
        })
        .fold(0.0, f32::max)
}

/// neuromod's L1 renormalization runs after every training step. When the
/// budget already holds it changes nothing, but float rounding can move a
/// weight by about one unit in the last place. Anything below this is that
/// rounding, not learning.
const RENORMALIZATION_ROUNDING: f32 = 1e-6;

#[test]
fn learning_happens_only_on_dopamine_steps_and_a_penalty_never_depresses() {
    let (trace, _) = replay(SCRIPTED_SESSION_SEED);
    let mut rewarded = 0;
    for step in &trace.steps {
        let largest = largest_weight_change(step);
        if step.modulators[0] > 0.0 {
            rewarded += 1;
            assert!(
                largest > 1e-3,
                "a delayed reward pays out eligibility traces (step {})",
                step.step
            );
        } else {
            assert!(
                largest <= RENORMALIZATION_ROUNDING,
                "neuromod converts traces into weight changes only with dopamine (step {})",
                step.step
            );
        }
    }
    assert_eq!(rewarded, 2);

    // A penalty right after a payout: still no learning, only the
    // renormalization pass settling the budget by rounding.
    let mut lab = PlasticityLab::new(SCRIPTED_SESSION_SEED);
    lab.step(Stimulus::PatternA, RewardEvent::None)
        .expect("step");
    let reward = lab
        .step(Stimulus::Quiet, RewardEvent::Reward)
        .expect("step");
    assert!(largest_weight_change(&reward) > 1e-3);
    let penalty = lab
        .step(Stimulus::Quiet, RewardEvent::Penalty)
        .expect("step");
    assert_eq!(penalty.modulators, [0.0, 0.0, 0.0, 1.0]);
    assert!(largest_weight_change(&penalty) <= RENORMALIZATION_ROUNDING);
    // Norepinephrine scales neuromod's input gain down to 10 %, so the
    // pattern that fires both neurons without a penalty fires neither.
    let suppressed = lab
        .step(Stimulus::PatternB, RewardEvent::Penalty)
        .expect("step");
    assert!(suppressed.output_spikes.is_empty());
    assert_eq!(
        lab.step(Stimulus::PatternB, RewardEvent::None)
            .expect("step")
            .output_spikes,
        vec![0, 1]
    );
}

#[test]
fn the_rewarded_pattern_gains_weight_and_wins_the_frozen_probe() {
    let (trace, _) = replay(SCRIPTED_SESSION_SEED);
    for neuron in 0..LAB_NEURONS {
        let row = &trace.final_weights[neuron * LAB_CHANNELS..(neuron + 1) * LAB_CHANNELS];
        let pattern_a = row[0] + row[1];
        let pattern_b = row[2] + row[3];
        assert!(pattern_a > pattern_b, "neuron {neuron}: {row:?}");
        // neuromod renormalizes each neuron's weights to its L1 budget of 2.0.
        assert!((pattern_a + pattern_b - 2.0).abs() < 1e-5);
        assert!(
            trace.probe_before.pattern_a_spikes[neuron]
                == trace.probe_before.pattern_b_spikes[neuron]
        );
        assert!(
            trace.probe_after.pattern_a_spikes[neuron] > trace.probe_after.pattern_b_spikes[neuron]
        );
    }
}

#[test]
fn the_frozen_probe_leaves_the_session_untouched() {
    let mut lab = PlasticityLab::new(SCRIPTED_SESSION_SEED);
    for entry in &SCRIPTED_SESSION[..6] {
        lab.step(entry.stimulus, entry.event).expect("step");
    }
    let weights = lab.weights();
    let eligibility = lab.eligibility();
    let thresholds = lab.thresholds();
    let membranes = lab.membrane_potentials();
    let engine_step = lab.engine_step();
    let first = lab.probe().expect("probe");
    assert_eq!(lab.probe().expect("probe"), first);
    assert_eq!(lab.weights(), weights);
    assert_eq!(lab.eligibility(), eligibility);
    assert_eq!(lab.thresholds(), thresholds);
    assert_eq!(lab.membrane_potentials(), membranes);
    assert_eq!(lab.engine_step(), engine_step);

    // The session RNG is untouched too: probing mid-session does not change
    // what the remaining steps produce.
    let mut unprobed = PlasticityLab::new(SCRIPTED_SESSION_SEED);
    for entry in &SCRIPTED_SESSION[..6] {
        unprobed.step(entry.stimulus, entry.event).expect("step");
    }
    for entry in &SCRIPTED_SESSION[6..] {
        if entry.new_episode {
            lab.new_episode();
            unprobed.new_episode();
        }
        assert_eq!(
            lab.step(entry.stimulus, entry.event),
            unprobed.step(entry.stimulus, entry.event)
        );
    }
}

#[test]
fn a_reward_pays_every_live_trace_and_a_new_episode_discards_them() {
    let b_weight = |lab: &PlasticityLab| {
        let weights = lab.weights();
        weights[2] + weights[3]
    };
    // A penalty leaves pattern B's traces alive; a later reward in the same
    // episode pays them out, so B gains weight.
    let mut same_episode = PlasticityLab::new(SCRIPTED_SESSION_SEED);
    for _ in 0..3 {
        same_episode
            .step(Stimulus::PatternB, RewardEvent::None)
            .expect("step");
    }
    same_episode
        .step(Stimulus::Quiet, RewardEvent::Penalty)
        .expect("step");
    let before = b_weight(&same_episode);
    same_episode
        .step(Stimulus::Quiet, RewardEvent::Reward)
        .expect("step");
    assert!(b_weight(&same_episode) > before + 1e-3);

    // With a new episode in between, the reward has no trace left to pay.
    let mut new_episode = PlasticityLab::new(SCRIPTED_SESSION_SEED);
    for _ in 0..3 {
        new_episode
            .step(Stimulus::PatternB, RewardEvent::None)
            .expect("step");
    }
    new_episode.new_episode();
    let reward = new_episode
        .step(Stimulus::Quiet, RewardEvent::Reward)
        .expect("step");
    assert!(largest_weight_change(&reward) <= RENORMALIZATION_ROUNDING);
}

#[test]
fn a_new_episode_clears_traces_and_keeps_learned_weights() {
    let mut lab = PlasticityLab::new(SCRIPTED_SESSION_SEED);
    for entry in &SCRIPTED_SESSION[..6] {
        lab.step(entry.stimulus, entry.event).expect("step");
    }
    let weights = lab.weights();
    let thresholds = lab.thresholds();
    assert!(lab.eligibility().iter().any(|trace| *trace != 0.0));
    lab.new_episode();
    assert_eq!(lab.episode(), 2);
    assert_eq!(lab.engine_step(), 0);
    assert_eq!(lab.weights(), weights);
    assert_eq!(lab.thresholds(), thresholds);
    assert!(lab.eligibility().iter().all(|trace| *trace == 0.0));
    assert_eq!(lab.modulators(), [0.0; 4]);
}

#[test]
fn unknown_stimulus_and_event_codes_fail_closed() {
    assert!(
        Stimulus::parse(3)
            .unwrap_err()
            .starts_with("plasticity-stimulus-invalid:")
    );
    assert!(
        RewardEvent::parse(3)
            .unwrap_err()
            .starts_with("plasticity-event-invalid:")
    );
    for code in 0..=2 {
        assert_eq!(Stimulus::parse(code).unwrap() as u8, code);
        assert_eq!(RewardEvent::parse(code).unwrap() as u8, code);
    }
}

#[test]
fn the_lab_starts_from_the_documented_network() {
    let lab = PlasticityLab::new(SCRIPTED_SESSION_SEED);
    assert_eq!(
        lab.weights(),
        vec![INITIAL_WEIGHT; LAB_NEURONS * LAB_CHANNELS]
    );
    assert_eq!(lab.thresholds(), vec![INITIAL_THRESHOLD; LAB_NEURONS]);
    assert_eq!(lab.eligibility(), vec![0.0; LAB_NEURONS * LAB_CHANNELS]);
    assert_eq!(lab.completed_steps(), 0);
    assert_eq!(lab.episode(), 1);
    // Equal-share initialization over neuromod's L1 budget of 2.0.
    assert_eq!(INITIAL_WEIGHT * LAB_CHANNELS as f32, 2.0);
    assert_eq!(
        Stimulus::PatternA.vector(TRAINING_AMPLITUDE),
        [TRAINING_AMPLITUDE, TRAINING_AMPLITUDE, 0.0, 0.0]
    );
    assert_eq!(
        Stimulus::PatternB.vector(TRAINING_AMPLITUDE),
        [0.0, 0.0, TRAINING_AMPLITUDE, TRAINING_AMPLITUDE]
    );
}

#[test]
fn the_lab_links_the_pinned_plasticity_lab_revision_and_limbic_critic() {
    let lock = LOCKFILE.replace("\r\n", "\n");
    assert!(lock.contains(
        "name = \"plasticity-lab\"\nversion = \"0.2.1\"\nsource = \"git+https://github.com/Limen-Neural/plasticity-lab.git?rev=c80fac2eb96a140df9cfd999278bce414a329a56#c80fac2eb96a140df9cfd999278bce414a329a56\""
    ));
    assert!(lock.contains(
        "name = \"limbic-critic\"\nversion = \"0.3.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"0afb84406e35b755770254f4418c4b7b92b79c089f10e5c671b9ae2016a79329\""
    ));
    // A single neuromod in the graph: plasticity-lab drives the same 0.7.0
    // engine as the homepage adapter.
    assert_eq!(lock.matches("name = \"neuromod\"\n").count(), 1);
}

/// neuromod's eligibility traces call `f32::exp` (trace decay and the STDP
/// kernel), so the golden is only portable if every target rounds these
/// inputs the same way. Each value here is the correctly rounded result,
/// which the native, Node WASM, and browser replays all reproduce.
#[test]
fn exp_inputs_used_by_the_golden_round_identically() {
    let inputs = [-1.0 / TAU_ELIGIBILITY]
        .into_iter()
        .chain((1..=8).map(|dt| -(dt as f32) / 20.0));
    for input in inputs {
        let reference = (f64::from(input)).exp() as f32;
        assert_eq!(
            input.exp().to_bits(),
            reference.to_bits(),
            "exp({input}) is not correctly rounded on this target"
        );
    }
}

fn workspace_path(relative: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(relative)
}

/// Regenerate the committed golden (see the module docs for the command).
#[test]
#[ignore]
fn regenerate_plasticity_golden() {
    let path = workspace_path(GOLDEN_PATH);
    std::fs::create_dir_all(path.parent().expect("golden directory")).expect("create dir");
    std::fs::write(&path, generated_golden()).expect("write golden");
}
