//! Bit-exact golden-trace replay for the seed-9 browser runtime.
//!
//! `fixtures/seed9-trace.json` is generated by `regenerate_seed9_trace` (run
//! with `--ignored`). Expected values are never hand-edited: if upstream
//! behavior legitimately changes, regenerate the fixture instead.

use neuromorphic_adapter::BrowserRuntime;
use serde_json::Value;
use std::path::PathBuf;

const FIXTURE: &str = include_str!("fixtures/seed9-trace.json");

type StepRecord = (u64, u64, String, Vec<u32>, Vec<u32>);

fn replay(runtime: &mut BrowserRuntime, operations: &[Value]) -> Vec<StepRecord> {
    let mut steps = Vec::new();
    for operation in operations {
        match operation["op"].as_str().expect("operation kind") {
            "input" => {
                let sequence: u64 = operation["sequence"]
                    .as_str()
                    .expect("decimal u64 sequence")
                    .parse()
                    .expect("sequence parses");
                let samples: Vec<f32> = operation["samples"]
                    .as_array()
                    .expect("sample array")
                    .iter()
                    .map(|sample| sample.as_f64().expect("finite sample") as f32)
                    .collect();
                runtime
                    .input(sequence, &samples)
                    .expect("input is accepted");
            }
            "step" => {
                let state = runtime.step().expect("runtime can advance");
                steps.push((
                    state.completed_step,
                    state.last_sequence,
                    state.error_status,
                    state.spike_neurons,
                    state
                        .membrane_potentials
                        .iter()
                        .map(|potential| potential.to_bits())
                        .collect(),
                ));
            }
            other => panic!("unknown operation {other}"),
        }
    }
    steps
}

fn expected_step(expected: &Value) -> StepRecord {
    (
        expected["completed_step"]
            .as_str()
            .and_then(|value| value.parse().ok())
            .expect("decimal completed_step"),
        expected["last_sequence"]
            .as_str()
            .and_then(|value| value.parse().ok())
            .expect("decimal last_sequence"),
        expected["status"].as_str().expect("status").to_owned(),
        expected["spikes"]
            .as_array()
            .expect("spike array")
            .iter()
            .map(|spike| spike.as_u64().expect("spike index") as u32)
            .collect(),
        expected["potential_bits"]
            .as_array()
            .expect("potential bit array")
            .iter()
            .map(|bits| u32::from_str_radix(bits.as_str().expect("hex bits"), 16).unwrap())
            .collect(),
    )
}

#[test]
fn seed9_trace_matches_the_golden_fixture() {
    let fixture: Value = serde_json::from_str(FIXTURE).expect("fixture parses");
    let seed: u64 = fixture["seed"]
        .as_str()
        .and_then(|value| value.parse().ok())
        .expect("decimal seed");
    let operations = fixture["operations"].as_array().expect("operation list");
    let expected_steps: Vec<_> = operations
        .iter()
        .filter(|operation| operation["op"] == "step")
        .map(|operation| expected_step(&operation["expected"]))
        .collect();

    let mut runtime = BrowserRuntime::new(seed).expect("fixed topology is valid");
    let actual = replay(&mut runtime, operations);

    assert_eq!(actual.len(), expected_steps.len(), "step count");
    for (index, (actual_step, expected_step)) in actual.iter().zip(&expected_steps).enumerate() {
        assert_eq!(
            actual_step, expected_step,
            "step {index} diverged from the seed-9 golden trace"
        );
    }
    assert!(
        expected_steps.iter().any(|step| !step.3.is_empty()),
        "fixture must contain at least one spike"
    );
    // Delay coverage: upstream guarantees every edge delay is >= 1 tick
    // (`hash_delay` clamps to `max(1, max_delay)`), so no current is delivered
    // in the tick it was emitted. Assert that invariant on the live topology
    // and that some neuron fires on a step after a quiet step — a neuron that
    // did not fire has sub-threshold potential and decay only lowers it, so
    // firing without a fresh input can only come from a delayed mesh arrival.
    let delays = &runtime.state().topology_edge_delays;
    assert!(!delays.is_empty(), "topology must contain edges");
    let min_delay = *delays.iter().min().expect("non-empty delays");
    assert!(min_delay >= 1, "all edge delays must be >= 1 tick");
    let saw_spike_after_quiet_step = expected_steps
        .iter()
        .zip(expected_steps.iter().skip(1))
        .any(|(previous, current)| previous.3.is_empty() && !current.3.is_empty());
    assert!(
        saw_spike_after_quiet_step,
        "fixture must exercise a delayed arrival: a spike on a step after a quiet step"
    );
}

/// Regenerate the fixture: `cargo test regenerate_seed9_trace -- --ignored --exact`.
#[test]
#[ignore]
fn regenerate_seed9_trace() {
    let operations = serde_json::json!([
        {"op": "input", "sequence": "1", "samples": [1.0, 0.0, 0.5, 0.25]},
        {"op": "input", "sequence": "2", "samples": [1.0, 0.75, 0.5, 0.25, 0.9, 0.1]},
        {"op": "step"},
        {"op": "input", "sequence": "3", "samples": [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3]},
        {"op": "input", "sequence": "4", "samples": [1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.5]},
        {"op": "step"},
        {"op": "step"},
        {"op": "step"},
        {"op": "step"},
        {"op": "step"},
        {"op": "input", "sequence": "5", "samples": [0.2, 0.4, 0.6, 0.8, 1.0, 0.8, 0.6, 0.4]},
        {"op": "step"},
        {"op": "step"},
        {"op": "step"},
        {"op": "step"},
        {"op": "step"},
        {"op": "step"},
    ]);
    let seed: u64 = 9;
    let mut runtime = BrowserRuntime::new(seed).expect("fixed topology is valid");
    let mut completed = Vec::new();
    for operation in operations.as_array().unwrap() {
        if operation["op"] == "step" {
            let state = runtime.step().expect("runtime can advance");
            completed.push(serde_json::json!({
                "completed_step": state.completed_step.to_string(),
                "last_sequence": state.last_sequence.to_string(),
                "status": state.error_status,
                "spikes": state.spike_neurons,
                "potential_bits": state
                    .membrane_potentials
                    .iter()
                    .map(|potential| format!("{:08x}", potential.to_bits()))
                    .collect::<Vec<_>>(),
            }));
        } else {
            let sequence: u64 = operation["sequence"].as_str().unwrap().parse().unwrap();
            let samples: Vec<f32> = operation["samples"]
                .as_array()
                .unwrap()
                .iter()
                .map(|sample| sample.as_f64().unwrap() as f32)
                .collect();
            runtime
                .input(sequence, &samples)
                .expect("input is accepted");
        }
    }
    let mut output = operations.clone();
    let mut step_index = 0;
    for operation in output.as_array_mut().unwrap() {
        if operation["op"] == "step" {
            operation["expected"] = completed[step_index].clone();
            step_index += 1;
        }
    }
    let fixture = serde_json::json!({ "seed": seed.to_string(), "operations": output });
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/seed9-trace.json");
    std::fs::write(
        &path,
        serde_json::to_string_pretty(&fixture).unwrap() + "\n",
    )
    .expect("fixture is writable");
    eprintln!("wrote {}", path.display());
}
